### ISSUE TITLE
App crashes when I click on MixedAudio option

### ISSUE THREAD

**Issue by abh1kr** [legendsayantan/ShizuTools#3]
The app crashes every time I click on MixedAudio option. I've tried this for multiple times and I am running Android 14 on a Samsung device with OneUI 6.1

**Comment by legendsayantan** [comment]
Thanks for the report, it will help the development process.

**Comment by 0-BlackSpectrum-0** [comment]
Same here:
```
FATAL EXCEPTION: Thread-2
Process: com.legendsayantan.adbtools, PID: 14274
java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.legendsayantan.adbtools/output.txt: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
	at com.legendsayantan.adbtools.lib.Utils$Companion.lastCommandOutput(Utils.kt:88)
	at com.legendsayantan.adbtools.MixedAudioActivity.reloadApps(MixedAudioActivity.kt:39)
	at com.legendsayantan.adbtools.MixedAudioActivity.onCreate$lambda$0(MixedAudioActivity.kt:27)
	at com.legendsayantan.adbtools.MixedAudioActivity.$r8$lambda$ffJ1Hu0qdhSzXuG9R_Gei9N-uj0(Unknown Source:0)
	at com.legendsayantan.adbtools.MixedAudioActivity$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8514)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 9 more
```
Samsung M30s Android 11 with One UI 3.1
[Logs](https://files.catbox.moe/thkxsx.log)

**Comment by Mujtaba0150** [comment]
E/AndroidRuntime( 3771): Process: com.legendsayantan.adbtools, PID: 3771
E/AndroidRuntime( 3771): Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.legendsayantan.adbtools/output.txt: open failed: ENOENT (No such file or directory)
E/AndroidRuntime( 3771):        at com.legendsayantan.adbtools.lib.Utils$Companion.lastCommandOutput(Utils.kt:88)
E/AndroidRuntime( 3771):        at com.legendsayantan.adbtools.MainActivity.openShell$lambda$7(MainActivity.kt:67)
E/AndroidRuntime( 3771):        at com.legendsayantan.adbtools.MainActivity.$r8$lambda$HUbNbzAjCoWotCgHAIPXHu3tGN4(Unknown Source:0)
E/AndroidRuntime( 3771):        at com.legendsayantan.adbtools.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:6)
E/WindowManager( 1449): win=Window{87a71e4 u0 com.legendsayantan.adbtools/com.legendsayantan.adbtools.MainActivity EXITING} destroySurfaces: appStopped=false cleanupOnResume=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.WindowState.onExitAnimationDone:5997 com.android.server.wm.WindowStateAnimator.onAnimationFinished:225 com.android.server.wm.WindowState.onAnimationFinished:6222 com.android.server.wm.WindowContainer$$ExternalSyntheticLambda4.onAnimationFinished:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:140 com.android.server.wm.SurfaceAnimator.$r8$lambda$lRxTVOJy8fX752UbrFno9INW9hE:0 com.android.server.wm.SurfaceAnimator$$ExternalSyntheticLambda1.run:8

**Comment by legendsayantan** [comment]
This issue should not occur anymore on the latest available apk file.
