### ISSUE TITLE
SoundMaster does not show any apps when adding slider

### ISSUE THREAD

**Issue by wouterroos** [legendsayantan/ShizuTools#30]
Hi,

I can't get SoundMaster to work on my Pixel 7 Pro. When I try to add a slider the list on the top stays empty and there seems to be no way to select an app.

Thanks!

**Comment by legendsayantan** [comment]
You might need to wait for some time for ShizuTools to fetch the information about installed apps. If it still doesn't work, try installing a different build of ShizuTools.

**Comment by wouterroos** [comment]
I tried again and waited for 10 minutes but no luck unfortunately. Which other version do you recommend?

**Comment by wouterroos** [comment]
I tried again and waited for 10 minutes but no luck unfortunately. Which other version do you recommend?

**Comment by legendsayantan** [comment]
There are two different apk files available for download on the Readme file, dev and release.

**Comment by wouterroos** [comment]
> There are two different apk files available for download on the Readme file, dev and release.

I tried both the release and dev version but no luck. BTW, on the dev version MixedAudio also doesn't show any apps so I reverted to the release version. Please let me know if I can provide any information towards fixing the issue!

**Comment by markran** [comment]
I have the same problem on my Samsung Note20 Ultra. Tried both release and dev versions. Waited a long time. After about 90 seconds the ShizuTools overlay disappears so maybe the app exited.

My goal is to silence Google Gemini AI. Stupid app keeps talking and has no option to silence it. Samsung SoundAssistant app doesn't show Gemini app and muting Google Assistant doesn't work.

**Comment by legendsayantan** [comment]
@wouterroos Strangely, the Pixel 7 Pro emulator I used to test did not show any issues and worked properly. It seems this issue is hard to reproduce on my end and for that reason, The dev build now has error logging enabled. Try dev build again, and once something doesn't work, submit the logs if you would want to help debug this issue.

**Comment by N-U-ser** [comment]
### Logs for Error on my Device
java.io.FileNotFoundException: /data/user/10/com.legendsayantan.adbtools/files/soundmaster.txt: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:179)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
	at com.legendsayantan.adbtools.SoundMasterActivity.getPackageSliders(SoundMasterActivity.kt:44)
	at com.legendsayantan.adbtools.SoundMasterActivity.updateSliders(SoundMasterActivity.kt:252)
	at com.legendsayantan.adbtools.SoundMasterActivity.onResume(SoundMasterActivity.kt:137)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1584)
	at android.app.Activity.performResume(Activity.java:8690)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5038)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5082)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8170)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 22 more


java.io.FileNotFoundException: /data/user/10/com.legendsayantan.adbtools/files/soundmaster.txt: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:179)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
	at com.legendsayantan.adbtools.SoundMasterActivity.getPackageSliders(SoundMasterActivity.kt:44)
	at com.legendsayantan.adbtools.SoundMasterActivity.updateSliders$lambda$15(SoundMasterActivity.kt:255)
	at com.legendsayantan.adbtools.SoundMasterActivity.$r8$lambda$jTBF2DEAwQYTN2C0ALuM8ibpiFI(Unknown Source:0)
	at com.legendsayantan.adbtools.SoundMasterActivity$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8170)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 8 more


java.io.FileNotFoundException: /data/user/10/com.legendsayantan.adbtools/files/soundmaster.txt: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:179)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
	at com.legendsayantan.adbtools.SoundMasterActivity.getPackageSliders(SoundMasterActivity.kt:44)
	at com.legendsayantan.adbtools.SoundMasterActivity.updateSliders(SoundMasterActivity.kt:252)
	at com.legendsayantan.adbtools.SoundMasterActivity.onResume(SoundMasterActivity.kt:137)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1584)
	at android.app.Activity.performResume(Activity.java:8690)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5038)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5082)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8170)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 22 more


java.io.FileNotFoundException: /data/user/10/com.legendsayantan.adbtools/files/soundmaster.txt: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:179)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
	at com.legendsayantan.adbtools.SoundMasterActivity.getPackageSliders(SoundMasterActivity.kt:44)
	at com.legendsayantan.adbtools.SoundMasterActivity.updateSliders$lambda$15(SoundMasterActivity.kt:255)
	at com.legendsayantan.adbtools.SoundMasterActivity.$r8$lambda$jTBF2DEAwQYTN2C0ALuM8ibpiFI(Unknown Source:0)
	at com.legendsayantan.adbtools.SoundMasterActivity$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8170)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 8 more


java.io.FileNotFoundException: /data/user/10/com.legendsayantan.adbtools/files/soundmaster.txt: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:179)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
	at com.legendsayantan.adbtools.SoundMasterActivity.getPackageSliders(SoundMasterActivity.kt:44)
	at com.legendsayantan.adbtools.SoundMasterActivity.updateBtnState$lambda$9(SoundMasterActivity.kt:148)
	at com.legendsayantan.adbtools.SoundMasterActivity.$r8$lambda$CLacybiCF8qKfyE0_7SxcS12N7I(Unknown Source:0)
	at com.legendsayantan.adbtools.SoundMasterActivity$$ExternalSyntheticLambda4.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7575)
	at android.view.View.performClickInternal(View.java:7548)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29848)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8170)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 19 more

### And Some Visual Aid
1)![Screenshot_2024-10-03-11-56-37-829_com legendsayantan adbtools](https://github.com/user-attachments/assets/c3211cfa-d49f-441f-8be9-bb306d753e14)
2)
![Screenshot_2024-10-03-11-56-47-503_com legendsayantan adbtools](https://github.com/user-attachments/assets/0e79258d-771e-4f1b-bc2a-165a411405b4)
3)
![Screenshot_2024-10-03-11-56-49-673_com legendsayantan adbtools](https://github.com/user-attachments/assets/2ab3d506-6fdc-4199-9868-daaf92dbe528)
4)
![Screenshot_2024-10-03-11-56-53-828_com legendsayantan adbtools](https://github.com/user-attachments/assets/d4dcf3af-cc8c-4f8b-bd94-6a85a69164a0)

**MY DEVICE SPECIFICATION**
Redmi Note 11T 
Android 13
Miui 14
SecondSpace  ,i.e., UserId 10

**I have tested ShizuTools' Previous version in First space, UserId 0 , too. That version didn't load any apps list either and also didn't show any kind of toast that says it is loading.**

**Comment by wouterroos** [comment]
Hi,

I updated to the latest dev build just now and everything works fine on this one. The app list opens as expected and I'm able to add sliders!

**Comment by N-U-ser** [comment]
## It is Working Now.
### Used the dev build. And it works fines.
1)
![Screenshot_2024-10-04-10-57-21-559_com legendsayantan adbtools](https://github.com/user-attachments/assets/26000154-e572-4129-b7f4-1c205dffa53b)
![Screenshot_2024-10-04-10-57-04-148_com legendsayantan adbtools](https://github.com/user-attachments/assets/7e20b22d-6b9b-47c8-aa4e-023345c5c47d)

_I have some other feature request for Sound Master such as Changing the volume and other values by intent or as tasker plugin, i will open an issue for this. Anyway thanks._

**Comment by N-U-ser** [comment]
# Bug : Searched/ Filtered app doesn't get selected

**When done searching and selecting from filtered list. The selected app get replaced with the app in unfiltered list, which is at the same position from top. For example, 2nd from top.**

## Searching/ Filtering is pretty much Non-existent (due to being non-functional)

[Test_Recording.webm](https://github.com/user-attachments/assets/f0471f5b-1f98-486d-bb22-e2aef63da18c)

**Comment by legendsayantan** [comment]
@N-U-ser I see, will fix asap.

**Comment by legendsayantan** [comment]
Closing for inactivity.
