### ISSUE TITLE
MixedAudio not working 

### ISSUE THREAD

**Issue by AbhishekR14** [legendsayantan/ShizuTools#35]
I am using pixel9 on Android 15 and MixedAudio is not working ![Screenshot_20241018-165404.png](https://github.com/user-attachments/assets/1e7b3fe4-88c1-451b-98a8-be323ee56517)

**Comment by AbhishekR14** [comment]
java.lang.IllegalStateException: binder haven't been received
	at rikka.shizuku.Shizuku.requireService(Shizuku.java:430)
	at rikka.shizuku.Shizuku.checkSelfPermission(Shizuku.java:868)
	at com.legendsayantan.adbtools.InitialActivity.checkPermission(InitialActivity.kt:78)
	at com.legendsayantan.adbtools.InitialActivity.onCreate(InitialActivity.kt:36)
	at android.app.Activity.performCreate(Activity.java:9002)
	at android.app.Activity.performCreate(Activity.java:8980)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by legendsayantan** [comment]
Does opening shizuku app shows any warning or error?

**Comment by AbhishekR14** [comment]
Nope Shizuku app runs without any errors

**Comment by OrAngEFanAtiC** [comment]
mixed audio not working, using pixel 7a android 15 
it worked fine till october 15th the day i upgraded to android 15

**Comment by legendsayantan** [comment]
@AbhishekR14  when sharing logs, could you select on the "Shizuku" section of the logs and share those?

**Comment by AbhishekR14** [comment]
> @AbhishekR14  when sharing logs, could you select on the "Shizuku" section of the logs and share those?

Yes sure
Error: java.lang.SecurityException: Shell does not have permission to access user 10
 com.android.server.am.ActivityManagerService.handleIncomingUser:14121 android.app.ActivityManager.handleIncomingUser:5198 com.android.server.pm.PackageManagerShellCommand.translateUserId:3947

**Comment by ZeeshanRabbani** [comment]
having similar issue Android 11 realme pad. the app launches fine mixed audio is working but whenever i minimise the app, the audio goes away.

**Comment by legendsayantan** [comment]
@AbhishekR14 I suppose you have work profile on your device and that is interfering. I have attempted to implement an workaround, which can be found at the current dev release.

**Comment by AbhishekR14** [comment]
@legendsayantan Thank you very much for your hard work!
And yes you are right, i do have a work profile, let me update the app and give it a try

**Comment by AbhishekR14** [comment]
@legendsayantan I have just tested it out, and i can confirm that it works now! Thank you for all your hard work and quick fix!!

**Comment by legendsayantan** [comment]
@ZeeshanRabbani  @OrAngEFanAtiC  Can you share the logs from the app? it'll help me diagnose the cause of your problem.

**Comment by OrAngEFanAtiC** [comment]
@legendsayantan 

java.lang.IllegalStateException: binder haven't been received
	at rikka.shizuku.Shizuku.requireService(Shizuku.java:430)
	at rikka.shizuku.Shizuku.checkSelfPermission(Shizuku.java:868)
	at com.legendsayantan.adbtools.InitialActivity.checkPermission(InitialActivity.kt:78)
	at com.legendsayantan.adbtools.InitialActivity.onCreate(InitialActivity.kt:36)
	at android.app.Activity.performCreate(Activity.java:8960)
	at android.app.Activity.performCreate(Activity.java:8938)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3975)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)


java.lang.IllegalStateException: binder haven't been received
	at rikka.shizuku.Shizuku.requireService(Shizuku.java:430)
	at rikka.shizuku.Shizuku.checkSelfPermission(Shizuku.java:868)
	at com.legendsayantan.adbtools.InitialActivity.checkPermission(InitialActivity.kt:78)
	at com.legendsayantan.adbtools.InitialActivity.onResume(InitialActivity.kt:56)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1722)
	at android.app.Activity.performResume(Activity.java:9118)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5234)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5277)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:282)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)


java.io.FileNotFoundException: /data/user/0/com.legendsayantan.adbtools/files/soundmaster.txt: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:179)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
	at com.legendsayantan.adbtools.SoundMasterActivity.getPackageSliders(SoundMasterActivity.kt:44)
	at com.legendsayantan.adbtools.SoundMasterActivity.updateSliders(SoundMasterActivity.kt:252)
	at com.legendsayantan.adbtools.SoundMasterActivity.onResume(SoundMasterActivity.kt:137)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1722)
	at android.app.Activity.performResume(Activity.java:9118)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5234)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5277)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:282)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8478)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 23 more


java.io.FileNotFoundException: /data/user/0/com.legendsayantan.adbtools/files/soundmaster.txt: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:179)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
	at com.legendsayantan.adbtools.SoundMasterActivity.getPackageSliders(SoundMasterActivity.kt:44)
	at com.legendsayantan.adbtools.SoundMasterActivity.updateSliders$lambda$15(SoundMasterActivity.kt:255)
	at com.legendsayantan.adbtools.SoundMasterActivity.$r8$lambda$jTBF2DEAwQYTN2C0ALuM8ibpiFI(Unknown Source:0)
	at com.legendsayantan.adbtools.SoundMasterActivity$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8478)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 8 more


java.io.FileNotFoundException: /data/user/0/com.legendsayantan.adbtools/files/soundmaster.txt: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:179)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
	at com.legendsayantan.adbtools.SoundMasterActivity.getPackageSliders(SoundMasterActivity.kt:44)
	at com.legendsayantan.adbtools.SoundMasterActivity.access$getPackageSliders(SoundMasterActivity.kt:39)
	at com.legendsayantan.adbtools.SoundMasterActivity$onCreate$1$1$1.invoke(SoundMasterActivity.kt:94)
	at com.legendsayantan.adbtools.SoundMasterActivity$onCreate$1$1$1.invoke(SoundMasterActivity.kt:106)
	at com.legendsayantan.adbtools.dialog.OutputSelectionDialog$show$adapter$1.invoke(OutputSelectionDialog.kt:32)
	at com.legendsayantan.adbtools.dialog.OutputSelectionDialog$show$adapter$1.invoke(OutputSelectionDialog.kt:30)
	at com.legendsayantan.adbtools.adapters.SimpleAdapter.onBindViewHolder$lambda$0(SimpleAdapter.kt:22)
	at com.legendsayantan.adbtools.adapters.SimpleAdapter.$r8$lambda$CLDCEG0HoCp8sFHTaRn9EjeRUyE(Unknown Source:0)
	at com.legendsayantan.adbtools.adapters.SimpleAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7931)
	at android.view.View.performClickInternal(View.java:7908)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30990)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8478)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 24 more


java.io.FileNotFoundException: /data/user/0/com.legendsayantan.adbtools/files/soundmaster.txt: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:179)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
	at com.legendsayantan.adbtools.SoundMasterActivity.getPackageSliders(SoundMasterActivity.kt:44)
	at com.legendsayantan.adbtools.SoundMasterActivity.access$getPackageSliders(SoundMasterActivity.kt:39)
	at com.legendsayantan.adbtools.SoundMasterActivity$onCreate$1$1$1.invoke(SoundMasterActivity.kt:96)
	at com.legendsayantan.adbtools.SoundMasterActivity$onCreate$1$1$1.invoke(SoundMasterActivity.kt:106)
	at com.legendsayantan.adbtools.dialog.OutputSelectionDialog$show$adapter$1.invoke(OutputSelectionDialog.kt:32)
	at com.legendsayantan.adbtools.dialog.OutputSelectionDialog$show$adapter$1.invoke(OutputSelectionDialog.kt:30)
	at com.legendsayantan.adbtools.adapters.SimpleAdapter.onBindViewHolder$lambda$0(SimpleAdapter.kt:22)
	at com.legendsayantan.adbtools.adapters.SimpleAdapter.$r8$lambda$CLDCEG0HoCp8sFHTaRn9EjeRUyE(Unknown Source:0)
	at com.legendsayantan.adbtools.adapters.SimpleAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7931)
	at android.view.View.performClickInternal(View.java:7908)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30990)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8478)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 24 more


java.lang.IllegalStateException: binder haven't been received
	at rikka.shizuku.Shizuku.requireService(Shizuku.java:430)
	at rikka.shizuku.Shizuku.checkSelfPermission(Shizuku.java:868)
	at com.legendsayantan.adbtools.InitialActivity.checkPermission(InitialActivity.kt:78)
	at com.legendsayantan.adbtools.InitialActivity.onCreate(InitialActivity.kt:36)
	at android.app.Activity.performCreate(Activity.java:9002)
	at android.app.Activity.performCreate(Activity.java:8980)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)


java.lang.IllegalStateException: binder haven't been received
	at rikka.shizuku.Shizuku.requireService(Shizuku.java:430)
	at rikka.shizuku.Shizuku.checkSelfPermission(Shizuku.java:868)
	at com.legendsayantan.adbtools.InitialActivity.checkPermission(InitialActivity.kt:78)
	at com.legendsayantan.adbtools.InitialActivity.onResume(InitialActivity.kt:56)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1722)
	at android.app.Activity.performResume(Activity.java:9160)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5299)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5342)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:107)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)


java.lang.IllegalStateException: binder haven't been received
	at rikka.shizuku.Shizuku.requireService(Shizuku.java:430)
	at rikka.shizuku.Shizuku.checkSelfPermission(Shizuku.java:868)
	at com.legendsayantan.adbtools.InitialActivity.checkPermission(InitialActivity.kt:78)
	at com.legendsayantan.adbtools.InitialActivity.onResume(InitialActivity.kt:56)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1722)
	at android.app.Activity.performResume(Activity.java:9160)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5299)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5342)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:107)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)


java.lang.IllegalStateException: binder haven't been received
	at rikka.shizuku.Shizuku.requireService(Shizuku.java:430)
	at rikka.shizuku.Shizuku.checkSelfPermission(Shizuku.java:868)
	at com.legendsayantan.adbtools.InitialActivity.checkPermission(InitialActivity.kt:78)
	at com.legendsayantan.adbtools.InitialActivity.onCreate(InitialActivity.kt:36)
	at android.app.Activity.performCreate(Activity.java:9002)
	at android.app.Activity.performCreate(Activity.java:8980)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)


java.lang.IllegalStateException: binder haven't been received
	at rikka.shizuku.Shizuku.requireService(Shizuku.java:430)
	at rikka.shizuku.Shizuku.checkSelfPermission(Shizuku.java:868)
	at com.legendsayantan.adbtools.InitialActivity.checkPermission(InitialActivity.kt:78)
	at com.legendsayantan.adbtools.InitialActivity.onResume(InitialActivity.kt:56)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1722)
	at android.app.Activity.performResume(Activity.java:9160)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5299)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5342)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:107)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by OrAngEFanAtiC** [comment]
I also tried installing the dev build but it also didn't work and yes I have the 2nd profile switched on from android 15

**Comment by legendsayantan** [comment]
@OrAngEFanAtiC did you download the dev build within the last two days?

**Comment by OrAngEFanAtiC** [comment]
> @AbhishekR14 I suppose you have work profile on your device and that is interfering. I have attempted to implement an workaround, which can be found at the current dev build.

After I saw this comment I downloaded 
![Screenshot_20241024-200327](https://github.com/user-attachments/assets/e6d9f2fa-9bca-4884-81b2-33dfa3c14127)
