### ISSUE TITLE
Mixed audio not working

### ISSUE THREAD

**Issue by OrAngEFanAtiC** [legendsayantan/ShizuTools#44]
im using pixel 7a 1.4.6  , it worked before updating to android 15 but since updating it stopped there was another thread on this issue that mentioned the reason is probably having a private user profile and i tried to use mixed audio again after deleting the private user profile it still doesnt work

**Comment by OrAngEFanAtiC** [comment]
android.content.pm.PackageManager$NameNotFoundException: 
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:528)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:511)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:505)
	at com.legendsayantan.adbtools.MixedAudioActivity.getAppName(MixedAudioActivity.kt:214)
	at com.legendsayantan.adbtools.MixedAudioActivity.access$getAppName(MixedAudioActivity.kt:26)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:149)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:141)
	at com.legendsayantan.adbtools.lib.Utils$Companion$loadApps$2.onCommandResult(Utils.kt:98)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.command$lambda$2(ShizukuRunner.kt:52)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.$r8$lambda$S18ye_JXsv_Sqf5DkGslXtuewcA(Unknown Source:0)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)


android.content.pm.PackageManager$NameNotFoundException: 
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:528)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:511)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:505)
	at com.legendsayantan.adbtools.MixedAudioActivity.getAppName(MixedAudioActivity.kt:214)
	at com.legendsayantan.adbtools.MixedAudioActivity.access$getAppName(MixedAudioActivity.kt:26)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:149)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:141)
	at com.legendsayantan.adbtools.lib.Utils$Companion$loadApps$2.onCommandResult(Utils.kt:98)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.command$lambda$2(ShizukuRunner.kt:52)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.$r8$lambda$S18ye_JXsv_Sqf5DkGslXtuewcA(Unknown Source:0)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)


android.content.pm.PackageManager$NameNotFoundException: 
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:528)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:511)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:505)
	at com.legendsayantan.adbtools.MixedAudioActivity.getAppName(MixedAudioActivity.kt:214)
	at com.legendsayantan.adbtools.MixedAudioActivity.access$getAppName(MixedAudioActivity.kt:26)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:149)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:141)
	at com.legendsayantan.adbtools.lib.Utils$Companion$loadApps$2.onCommandResult(Utils.kt:98)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.command$lambda$2(ShizukuRunner.kt:52)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.$r8$lambda$S18ye_JXsv_Sqf5DkGslXtuewcA(Unknown Source:0)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)


android.content.pm.PackageManager$NameNotFoundException: 
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:528)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:511)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:505)
	at com.legendsayantan.adbtools.MixedAudioActivity.getAppName(MixedAudioActivity.kt:214)
	at com.legendsayantan.adbtools.MixedAudioActivity.access$getAppName(MixedAudioActivity.kt:26)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:149)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:141)
	at com.legendsayantan.adbtools.lib.Utils$Companion$loadApps$2.onCommandResult(Utils.kt:98)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.command$lambda$2(ShizukuRunner.kt:52)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.$r8$lambda$S18ye_JXsv_Sqf5DkGslXtuewcA(Unknown Source:0)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)


android.content.pm.PackageManager$NameNotFoundException: 
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:528)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:511)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:505)
	at com.legendsayantan.adbtools.MixedAudioActivity.getAppName(MixedAudioActivity.kt:214)
	at com.legendsayantan.adbtools.MixedAudioActivity.access$getAppName(MixedAudioActivity.kt:26)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:149)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:141)
	at com.legendsayantan.adbtools.lib.Utils$Companion$loadApps$2.onCommandResult(Utils.kt:98)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.command$lambda$2(ShizukuRunner.kt:52)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.$r8$lambda$S18ye_JXsv_Sqf5DkGslXtuewcA(Unknown Source:0)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)


android.content.pm.PackageManager$NameNotFoundException: 
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:528)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:511)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:505)
	at com.legendsayantan.adbtools.MixedAudioActivity.getAppName(MixedAudioActivity.kt:214)
	at com.legendsayantan.adbtools.MixedAudioActivity.access$getAppName(MixedAudioActivity.kt:26)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:149)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:141)
	at com.legendsayantan.adbtools.lib.Utils$Companion$loadApps$2.onCommandResult(Utils.kt:98)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.command$lambda$2(ShizukuRunner.kt:52)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.$r8$lambda$S18ye_JXsv_Sqf5DkGslXtuewcA(Unknown Source:0)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)


android.content.pm.PackageManager$NameNotFoundException: 
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:528)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:511)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:505)
	at com.legendsayantan.adbtools.MixedAudioActivity.getAppName(MixedAudioActivity.kt:214)
	at com.legendsayantan.adbtools.MixedAudioActivity.access$getAppName(MixedAudioActivity.kt:26)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:149)
	at com.legendsayantan.adbtools.MixedAudioActivity$reloadApps$1$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2$onCommandResult$2.invoke(MixedAudioActivity.kt:141)
	at com.legendsayantan.adbtools.lib.Utils$Companion$loadApps$2.onCommandResult(Utils.kt:98)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.command$lambda$2(ShizukuRunner.kt:52)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion.$r8$lambda$S18ye_JXsv_Sqf5DkGslXtuewcA(Unknown Source:0)
	at com.legendsayantan.adbtools.lib.ShizukuRunner$Companion$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by burroughsb5795** [comment]
ever find any resolution to this? I've also been having this issue recently.

**Comment by OrAngEFanAtiC** [comment]
it works now after downloading the latest dev build release 1 week ago

**Comment by legendsayantan** [comment]
I didn't even touch anything related to MixedAudio in this version... lmao

**Comment by girshcatt** [comment]
> I didn't even touch anything related to MixedAudio in this version... lmao

latest dev build has same issue for me
